<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.11">
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        <PrivateAssets>all</PrivateAssets>
      </PackageReference>
      <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.3" />
      <PackageReference Include="SixLabors.ImageSharp" Version="4.1.0" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Backend\Migrations\" />
      <Folder Include="ClientApp\scripts\" />
      <Folder Include="ClientApp\uploads\" />
    </ItemGroup>

    <ItemGroup>
      <Content Update="ClientApp\public\bf93dc6c-9dd3-4b45-992b-dcfc2ce64a1e.png">
        <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
        <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
      </Content>
      <Content Include=".idea\.idea.WebApplication6\.idea\.gitignore" />
      <Content Include=".idea\.idea.WebApplication6\.idea\dataSources.local.xml" />
      <Content Include=".idea\.idea.WebApplication6\.idea\dataSources.xml" />
      <Content Include=".idea\.idea.WebApplication6\.idea\dataSources\b3031635-74f6-4ba8-a379-d2fa60f239a2.xml" />
      <Content Include=".idea\.idea.WebApplication6\.idea\dataSources\b3031635-74f6-4ba8-a379-d2fa60f239a2\storage_v2\_src_\database\webapplication6.OhKEZw.meta" />
      <Content Include=".idea\.idea.WebApplication6\.idea\dataSources\b3031635-74f6-4ba8-a379-d2fa60f239a2\storage_v2\_src_\database\webapplication6.OhKEZw\schema\information_schema.FNRwLQ.meta" />
      <Content Include=".idea\.idea.WebApplication6\.idea\dataSources\b3031635-74f6-4ba8-a379-d2fa60f239a2\storage_v2\_src_\database\webapplication6.OhKEZw\schema\pg_catalog.0S1ZNQ.meta" />
      <Content Include=".idea\.idea.WebApplication6\.idea\dataSources\b3031635-74f6-4ba8-a379-d2fa60f239a2\storage_v2\_src_\database\webapplication6.OhKEZw\schema\public.abK9xQ.meta" />
      <Content Include=".idea\.idea.WebApplication6\.idea\dataSources\data_sources_history.xml" />
      <Content Include=".idea\.idea.WebApplication6\.idea\db-forest-config.xml" />
      <Content Include=".idea\.idea.WebApplication6\.idea\dictionaries\project.xml" />
      <Content Include=".idea\.idea.WebApplication6\.idea\indexLayout.xml" />
      <Content Include=".idea\.idea.WebApplication6\.idea\projectSettingsUpdater.xml" />
      <Content Include=".idea\.idea.WebApplication6\.idea\vcs.xml" />
      <Content Include=".idea\.idea.WebApplication6\.idea\workspace.xml" />
    </ItemGroup>

</Project>
